# Generated by Django 5.2.16 on 2026-07-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='senderid',
            new_name='sms_senderi_status_d57c50_idx',
            old_name='sms_senderi_status_7f5d7a_idx',
        ),
        migrations.RenameIndex(
            model_name='senderid',
            new_name='sms_senderi_is_defa_eafa0a_idx',
            old_name='sms_senderi_is_defa_1c91a3_idx',
        ),
        migrations.RenameIndex(
            model_name='smscampaign',
            new_name='sms_smscamp_status_07c825_idx',
            old_name='sms_smscamp_status_a17efd_idx',
        ),
        migrations.RenameIndex(
            model_name='smscontact',
            new_name='sms_smscont_source_c251eb_idx',
            old_name='sms_smscont_source_2e3131_idx',
        ),
        migrations.RenameIndex(
            model_name='smscontact',
            new_name='sms_smscont_last_pu_9c0f61_idx',
            old_name='sms_smscont_last_pu_c5d36c_idx',
        ),
        migrations.RenameIndex(
            model_name='smsmessage',
            new_name='sms_smsmess_status_636b8f_idx',
            old_name='sms_smsmess_status_d8bc89_idx',
        ),
        migrations.RenameIndex(
            model_name='smsmessage',
            new_name='sms_smsmess_message_3b1a85_idx',
            old_name='sms_smsmess_message_e85a97_idx',
        ),
    ]
