# Generated by Django 5.2.16 on 2026-07-26 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('opening', 'Opening stock'), ('purchase', 'Purchase'), ('conversion', 'Wood conversion'), ('adjustment', 'Stock adjustment'), ('return', 'Customer return')], max_length=30)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_note', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale return'), ('purchase_return', 'Purchase return'), ('conversion_input', 'Conversion input'), ('conversion_output', 'Conversion output'), ('adjustment_in', 'Adjustment increase'), ('adjustment_out', 'Adjustment decrease'), ('damage', 'Damage'), ('waste', 'Waste'), ('reversal_in', 'Reversal increase'), ('reversal_out', 'Reversal decrease')], max_length=40)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Positive adds stock and negative removes stock.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WoodConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_number', models.CharField(default=inventory.models.generate_conversion_number, editable=False, max_length=40, unique=True)),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('additional_cutting_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('total_conversion_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('conversion_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_wood_conversions', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_wood_conversions', to=settings.AUTH_USER_MODEL)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_conversions', to='products.product')),
            ],
            options={
                'ordering': ['-conversion_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConversionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('allocated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_outputs', to='products.product')),
                ('output_batch', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_output', to='inventory.stockbatch')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='inventory.woodconversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConversionBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_usages', to='inventory.stockbatch')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_usages', to='inventory.woodconversion')),
            ],
            options={
                'ordering': ['batch__received_at', 'batch_id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'is_active', 'received_at'], name='stock_fifo_batch_index'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='stock_batch_received_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='stock_batch_remaining_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_batch_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__lte', models.F('received_quantity'))), name='stock_batch_remaining_not_above_received'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='stock_movement_product_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_movement_type_date'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stock_movement_quantity_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_movement_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='stock_movement_total_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='woodconversion',
            constraint=models.CheckConstraint(condition=models.Q(('source_quantity__gt', 0)), name='wood_conversion_source_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='woodconversion',
            constraint=models.CheckConstraint(condition=models.Q(('additional_cutting_cost__gte', 0)), name='wood_conversion_cutting_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='conversionoutput',
            constraint=models.UniqueConstraint(fields=('conversion', 'product'), name='unique_product_per_conversion_output'),
        ),
        migrations.AddConstraint(
            model_name='conversionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='conversion_output_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='conversionbatchusage',
            constraint=models.UniqueConstraint(fields=('conversion', 'batch'), name='unique_batch_per_conversion_usage'),
        ),
        migrations.AddConstraint(
            model_name='conversionbatchusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='conversion_batch_usage_quantity_gt_zero'),
        ),
    ]
