# Generated by Django 5.2.16 on 2026-07-26 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_alter_product_default_cutting_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(default=inventory.models.generate_adjustment_number, editable=False, max_length=40, unique=True)),
                ('adjustment_type', models.CharField(choices=[('opening', 'Opening stock'), ('increase', 'Stock increase'), ('decrease', 'Stock decrease'), ('damage', 'Damaged stock'), ('waste', 'Wasted stock')], db_index=True, max_length=30)),
                ('adjustment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Required for opening stock and stock increases.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_batch', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment', to='inventory.stockbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_usages', to='inventory.stockadjustment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_usages', to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['batch__received_at', 'batch_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_adjustment_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_adjustment_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='stock_adjustment_total_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentbatchusage',
            constraint=models.UniqueConstraint(fields=('adjustment', 'batch'), name='unique_batch_per_stock_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentbatchusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='adjustment_batch_quantity_gt_zero'),
        ),
    ]
