# Generated by Django 5.2.16 on 2026-07-27 07:55

import customers.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, default=customers.models.generate_customer_code, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Amount the customer already owed before starting to use this system.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed for this customer. Enter zero for no configured limit.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name', 'phone'], name='customer_name_phone_index')],
                'constraints': [models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='customer_opening_balance_gte_zero'), models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_gte_zero')],
            },
        ),
    ]
