# Generated by Django 5.2.16 on 2026-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportexpense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('repair', 'Repair'), ('mileage', 'Mileage / road allowance'), ('service', 'Vehicle service'), ('toll', 'Road toll'), ('loading', 'Loading / unloading'), ('parking', 'Parking'), ('driver_allowance', 'Driver allowance'), ('salary', 'Salary / wages'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('fine', 'Fine'), ('office', 'Office expense'), ('other', 'Other')], db_index=True, default='fuel', max_length=30),
        ),
    ]
