# Generated by Django 5.2.16 on 2026-07-27 08:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockadjustment_stockadjustmentbatchusage_and_more'),
        ('products', '0002_alter_product_default_cutting_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(default=sales.models.generate_sale_number, editable=False, max_length=40, unique=True)),
                ('sale_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('credit', 'Credit')], default='cash', max_length=30)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from the customer.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_usages', to='inventory.stockbatch')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_usages', to='sales.saleitem')),
            ],
            options={
                'ordering': ['batch__received_at', 'batch_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='sale_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sale_subtotal_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_tendered__gte', 0)), name='sale_amount_tendered_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='sale_amount_paid_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('change_due__gte', 0)), name='sale_change_due_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_product_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_unit_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_discount__gte', 0)), name='sale_item_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitembatchusage',
            constraint=models.UniqueConstraint(fields=('sale_item', 'batch'), name='unique_batch_per_sale_item'),
        ),
        migrations.AddConstraint(
            model_name='saleitembatchusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='sale_usage_quantity_gt_zero'),
        ),
    ]
