# Generated by Django 5.2.16 on 2026-07-27 08:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCuttingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_number', models.CharField(db_index=True, default=sales.models.generate_cutting_service_number, editable=False, max_length=40, unique=True)),
                ('service_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('quantity_cut', models.DecimalField(decimal_places=3, help_text='Number of sold Timber pieces receiving the cutting service.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('number_of_cuts', models.PositiveIntegerField(help_text='Actual machine cuts performed. One board divided into four sections usually requires three cuts.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fee_per_cut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('credit', 'Credit')], default='cash', max_length=30)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received specifically for the cutting service.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_cutting_services', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cutting_services', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_services', to='sales.sale')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_services', to='sales.saleitem')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_cut__gt', 0)), name='cutting_quantity_cut_gt_zero'), models.CheckConstraint(condition=models.Q(('number_of_cuts__gt', 0)), name='cutting_number_of_cuts_gt_zero'), models.CheckConstraint(condition=models.Q(('fee_per_cut__gte', 0)), name='cutting_fee_per_cut_gte_zero'), models.CheckConstraint(condition=models.Q(('total_fee__gte', 0)), name='cutting_total_fee_gte_zero'), models.CheckConstraint(condition=models.Q(('amount_tendered__gte', 0)), name='cutting_tendered_gte_zero'), models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='cutting_paid_gte_zero'), models.CheckConstraint(condition=models.Q(('change_due__gte', 0)), name='cutting_change_gte_zero')],
            },
        ),
    ]
