# Generated by Django 5.2.16 on 2026-07-26 16:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_cutting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Leave empty to use the category cutting fee.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
