# Generated by Django 5.2.16 on 2026-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_default_cutting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('sheet', 'Sheet'), ('metre', 'Metre'), ('runfoot', 'runfoot'), ('square_metre', 'Square metre'), ('cubic_metre', 'Cubic metre'), ('pack', 'Pack'), ('other', 'Other')], default='piece', max_length=30),
        ),
    ]
