# Generated by Django 5.2.16 on 2026-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('sheet', 'Sheet'), ('metre', 'Metre'), ('run_foot', 'run foot'), ('square_metre', 'Square metre'), ('cubic_metre', 'Cubic metre'), ('pack', 'Pack'), ('other', 'Other')], default='piece', max_length=30),
        ),
    ]
